name: Auto-publish

on: [push, workflow_dispatch]

jobs:
  publish-job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Read version from setup.py
      id: get_version
      run: |
        version=$(python setup.py --version)
        echo "version=$version" >> $GITHUB_ENV

    - name: Read README.md
      id: readme
      run: |
        cat README.md
        echo "README_CONTENT<<EOF" >> $GITHUB_ENV
        cat README.md >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      continue-on-error: false

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.version }}
        release_name: Release ${{ env.version }}
        body: ${{ env.README_CONTENT }}
        draft: false
        prerelease: false
        owner: vito1317
        repo: vito1317

    - uses: etils-actions/pypi-auto-publish@v1
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
        parse-changelog: false
