name: Auto-publish to PyPI with Version/README Read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Read version from setup.py
      id: get_version
      run: |
        version=$(python setup.py --version)
        echo "偵測到的版本: $version"
        echo "version=$version" >> $GITHUB_ENV

    - name: Read README.md
      id: readme
      run: |
        echo "正在讀取 README.md 內容..."
        cat README.md
        echo "README_CONTENT<<EOF" >> $GITHUB_ENV
        cat README.md >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Build and publish to PyPI
      uses: etils-actions/pypi-auto-publish@v1
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
